- name: unarchive recdvb-1.3.2.tgz
  unarchive:
    src: http://www13.plala.or.jp/sat/recdvb/recdvb-1.3.2.tgz
    dest: /srv/tmp/
    remote_src: yes

- name: Run autogen.sh
  shell:
    cmd: ./autogen.sh
    chdir: /srv/tmp/recdvb-1.3.2
    creates: configure

- name: Run configure
  shell:
    cmd: ./configure --enable-b25
    chdir: /srv/tmp/recdvb-1.3.2
    creates: Makefile

- name: make recdvb
  make:
    chdir: /srv/tmp/recdvb-1.3.2

- name: make install recdvb
  make:
    chdir: /srv/tmp/recdvb-1.3.2
    target: install
  become: yes
