- name: Install pm2
  npm:
    name: pm2
    global: true

- name: Install mirakurun
  npm:
    name: mirakurun
    global: true
    unsafe_perm: true
    production: true

- name: copy tuners.yml
  copy:
    src: tuners.yml
    dest: /usr/local/etc/mirakurun/tuners.yml
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart_mirakurun
    - scan_channels
