- name: install apt-packages
  apt:
    name:
      - vim
      - git
      - build-essential
      - cmake # for libarib25
      - g++ # for libarib25
      - automake # for recdvb
      - autoconf # for recdvb
      - nodejs # for Mirakurun
      - npm # for Mirakurun
      - ffmpeg
    cache_valid_time: 3600
    update_cache: yes
